import { AnalysisResult } from "@/types";

export const mockAnalysis: AnalysisResult = {
  id: "demo-001",
  type: "pr",
  repoName: "vercel/next.js",
  prNumber: 71234,
  prTitle: "feat: add streaming SSR support for app router",
  prAuthor: "sophia-dev",
  overallScore: 72,
  complexityScore: 65,
  securityScore: 88,
  performanceScore: 58,
  maintainabilityScore: 74,
  totalAdditions: 847,
  totalDeletions: 234,
  filesChanged: 23,
  files: [
    {
      path: "src/app/router/streaming.tsx",
      additions: 234,
      deletions: 12,
      risk: "high",
      language: "TypeScript",
      complexity: 82,
      securityIssues: [
        {
          type: "XSS",
          severity: "medium",
          line: 45,
          description: "Unsanitized user input rendered in stream",
          suggestion: "Use dangerouslySetInnerHTML sanitization or DOMPurify",
        },
      ],
      performanceIssues: [
        {
          type: "Memory Leak",
          impact: "high",
          line: 89,
          description: "Stream reader not properly closed on unmount",
          suggestion: "Add cleanup in useEffect return function",
        },
      ],
    },
    {
      path: "src/lib/cache/invalidate.ts",
      additions: 156,
      deletions: 89,
      risk: "critical",
      language: "TypeScript",
      complexity: 91,
      securityIssues: [
        {
          type: "Prototype Pollution",
          severity: "critical",
          line: 23,
          description: "Object spread without prototype sanitization",
          suggestion: "Use Object.create(null) or hasOwnProperty check",
        },
      ],
      performanceIssues: [],
    },
    {
      path: "src/components/stream/suspense-boundary.tsx",
      additions: 189,
      deletions: 0,
      risk: "medium",
      language: "TypeScript",
      complexity: 56,
      securityIssues: [],
      performanceIssues: [
        {
          type: "Render Loop",
          impact: "medium",
          line: 34,
          description: "useEffect dependency may cause infinite re-renders",
          suggestion: "Add proper dependency array or use useCallback",
        },
      ],
    },
    {
      path: "src/server/render/stream.ts",
      additions: 145,
      deletions: 67,
      risk: "high",
      language: "TypeScript",
      complexity: 78,
      securityIssues: [],
      performanceIssues: [
        {
          type: "N+1 Query",
          impact: "high",
          line: 56,
          description: "Sequential data fetching in render loop",
          suggestion: "Batch requests with Promise.all or use streaming data",
        },
      ],
    },
    {
      path: "tests/streaming.test.ts",
      additions: 87,
      deletions: 12,
      risk: "low",
      language: "TypeScript",
      complexity: 32,
      securityIssues: [],
      performanceIssues: [],
    },
    {
      path: "src/config/stream.config.ts",
      additions: 34,
      deletions: 54,
      risk: "low",
      language: "TypeScript",
      complexity: 28,
      securityIssues: [],
      performanceIssues: [],
    },
    {
      path: "package.json",
      additions: 3,
      deletions: 0,
      risk: "low",
      language: "JSON",
      complexity: 5,
      securityIssues: [],
      performanceIssues: [],
    },
    {
      path: "src/utils/serialize.ts",
      additions: 0,
      deletions: 0,
      risk: "medium",
      language: "TypeScript",
      complexity: 64,
      securityIssues: [],
      performanceIssues: [
        {
          type: "CPU Blocking",
          impact: "medium",
          line: 12,
          description: "Synchronous serialization in hot path",
          suggestion: "Use structuredClone or async serialization",
        },
      ],
    },
  ],
  dependencies: [
    { source: "src/app/router/streaming.tsx", target: "src/server/render/stream.ts", type: "import", weight: 3 },
    { source: "src/app/router/streaming.tsx", target: "src/components/stream/suspense-boundary.tsx", type: "import", weight: 2 },
    { source: "src/app/router/streaming.tsx", target: "src/config/stream.config.ts", type: "import", weight: 1 },
    { source: "src/server/render/stream.ts", target: "src/lib/cache/invalidate.ts", type: "import", weight: 4 },
    { source: "src/server/render/stream.ts", target: "src/utils/serialize.ts", type: "import", weight: 2 },
    { source: "src/components/stream/suspense-boundary.tsx", target: "src/utils/serialize.ts", type: "import", weight: 1 },
    { source: "src/lib/cache/invalidate.ts", target: "src/config/stream.config.ts", type: "require", weight: 1 },
    { source: "tests/streaming.test.ts", target: "src/app/router/streaming.tsx", type: "import", weight: 2 },
    { source: "tests/streaming.test.ts", target: "src/server/render/stream.ts", type: "import", weight: 1 },
  ],
  reviews: [
    {
      id: "r1",
      priority: 1,
      category: "security",
      severity: "critical",
      file: "src/lib/cache/invalidate.ts",
      line: 23,
      title: "Prototype Pollution vulnerability",
      description: "Object spread without prototype sanitization allows attackers to inject properties into Object.prototype, potentially affecting all objects in the application.",
      suggestion: "Use Object.create(null) for cache keys or validate with hasOwnProperty before spreading.",
      effort: "quick",
    },
    {
      id: "r2",
      priority: 2,
      category: "performance",
      severity: "high",
      file: "src/app/router/streaming.tsx",
      line: 89,
      title: "Stream reader memory leak",
      description: "The ReadableStream reader is not properly closed when the component unmounts, leading to memory leaks during navigation.",
      suggestion: "Add reader.cancel() in the useEffect cleanup function.",
      effort: "quick",
    },
    {
      id: "r3",
      priority: 3,
      category: "performance",
      severity: "high",
      file: "src/server/render/stream.ts",
      line: 56,
      title: "N+1 data fetching pattern",
      description: "Sequential awaits in the render loop cause waterfall requests. Each stream chunk triggers a separate database query.",
      suggestion: "Batch data fetches with Promise.all() or implement a request coalescing layer.",
      effort: "moderate",
    },
    {
      id: "r4",
      priority: 4,
      category: "security",
      severity: "medium",
      file: "src/app/router/streaming.tsx",
      line: 45,
      title: "Potential XSS in stream rendering",
      description: "User-provided content is rendered without sanitization in the streaming response.",
      suggestion: "Apply DOMPurify or a custom sanitization function before rendering.",
      effort: "quick",
    },
    {
      id: "r5",
      priority: 5,
      category: "complexity",
      severity: "medium",
      file: "src/lib/cache/invalidate.ts",
      line: 1,
      title: "High cyclomatic complexity",
      description: "The invalidateCache function has a complexity score of 91, making it difficult to test and maintain.",
      suggestion: "Extract helper functions for each invalidation strategy. Consider splitting into separate modules.",
      effort: "significant",
    },
    {
      id: "r6",
      priority: 6,
      category: "performance",
      severity: "medium",
      file: "src/components/stream/suspense-boundary.tsx",
      line: 34,
      title: "Potential infinite re-render loop",
      description: "The useEffect dependency array includes an object that gets recreated on every render.",
      suggestion: "Memoize the dependency with useMemo or use useRef for mutable values.",
      effort: "quick",
    },
    {
      id: "r7",
      priority: 7,
      category: "architecture",
      severity: "medium",
      file: "src/server/render/stream.ts",
      line: 30,
      title: "Tight coupling between render and cache layers",
      description: "The streaming renderer directly imports and calls cache invalidation, violating separation of concerns.",
      suggestion: "Inject cache invalidation as a dependency or use an event bus pattern.",
      effort: "moderate",
    },
    {
      id: "r8",
      priority: 8,
      category: "performance",
      severity: "medium",
      file: "src/utils/serialize.ts",
      line: 12,
      title: "Synchronous serialization blocking main thread",
      description: "JSON.stringify is called synchronously in a hot path, potentially blocking the event loop.",
      suggestion: "Use worker-based serialization or structuredClone for large objects.",
      effort: "moderate",
    },
  ],
  summary: "This PR introduces streaming SSR support for the app router. While the core implementation is solid, there are critical security concerns around prototype pollution and a memory leak in the stream reader. The caching layer needs refactoring for separation of concerns. Recommend addressing the critical security issue and memory leak before merge.",
  analyzedAt: new Date().toISOString(),
};
